INHERIT: "../mkdocs.yml"
site_name: ue2rigify
site_url: https://poly-hammer.github.io/BlenderTools/ue2rigify/
docs_dir: '.'
nav:
  - Overview: "./index.md"
  - Quick Start: "./introduction/quickstart.md"
  - Concepts: 
    - Modes: "./concepts/modes.md"
    - Templates: "/concepts/templates.md"
  - Usage: 
    - Animation: "./usage/animation.md"
    - New Template Example: "./usage/new-template-example.md"
  - Advanced: 
    - Relink Constraints: "./advanced/relink-constraints.md"
  - Extras: 
    - Community Templates: "./extras/community-templates.md"
  - User Interface:
    - 3D View Panel: "./user-interface/3d-view-panel.md"
    - Node Editor Panel: "./user-interface/node-editor-panel.md"
    - Hotkeys: "./user-interface/hot-keys.md"
  - Trouble Shooting: 
    - FAQ: "./trouble-shooting/faq.md"
    - Errors: "./trouble-shooting/errors.md"